import { Boxes, Plus, Save, Trash2 } from "lucide-react";
import { createAdminProductVariantAction, deleteAdminProductVariantAction, updateAdminProductVariantAction } from "@/app/[locale]/admin/(protected)/products/assets/actions";

type Variant = { id: string; titleFa: string; titleEn: string; sku: string | null; price: {toString(): string} | null; stock: number; metalWeight: {toString(): string} | null; purity: string | null; purityFineness: number | null; makingChargeFixed: {toString(): string} | null; makingChargePerGram: {toString(): string} | null; makingChargePercent: {toString(): string} | null; artisticFee: {toString(): string} | null; attributes: unknown; isActive: boolean; displayOrder: number };
const input = "h-11 w-full rounded-xl border border-[#cfb45f]/20 bg-[#031a13] px-3 text-sm text-[#f7e7c2] outline-none placeholder:text-[#887c65] focus:border-[#dfc36d]/60";
function attrs(value: unknown) { const v = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; return { color: typeof v.color === "string" ? v.color : "", size: typeof v.size === "string" ? v.size : "", notes: typeof v.notes === "string" ? v.notes : "" }; }
function Fields({ variant }: { variant?: Variant }) { const a = attrs(variant?.attributes); return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
  <input className={input} defaultValue={variant?.titleFa ?? ""} name="titleFa" placeholder="عنوان فارسی *" required/><input className={input} defaultValue={variant?.titleEn ?? ""} dir="ltr" name="titleEn" placeholder="English title *" required/><input className={input} defaultValue={variant?.sku ?? ""} dir="ltr" name="sku" placeholder="SKU مستقل"/><input className={input} defaultValue={variant?.price?.toString() ?? ""} name="price" placeholder="قیمت مستقل"/>
  <input className={input} defaultValue={variant?.stock ?? 0} min="0" name="stock" type="number" placeholder="موجودی"/><input className={input} defaultValue={variant?.metalWeight?.toString() ?? ""} name="metalWeight" placeholder="وزن گرم"/><input className={input} defaultValue={variant?.purity ?? ""} name="purity" placeholder="عیار 18K"/><input className={input} defaultValue={variant?.purityFineness ?? ""} max="1000" name="purityFineness" type="number" placeholder="خلوص 750"/>
  <input className={input} defaultValue={a.color} name="color" placeholder="رنگ"/><input className={input} defaultValue={a.size} name="size" placeholder="سایز"/><input className={input} defaultValue={variant?.makingChargeFixed?.toString() ?? ""} name="makingChargeFixed" placeholder="اجرت ثابت"/><input className={input} defaultValue={variant?.makingChargePerGram?.toString() ?? ""} name="makingChargePerGram" placeholder="اجرت هر گرم"/>
  <input className={input} defaultValue={variant?.makingChargePercent?.toString() ?? ""} name="makingChargePercent" placeholder="اجرت درصدی"/><input className={input} defaultValue={variant?.artisticFee?.toString() ?? ""} name="artisticFee" placeholder="هزینه هنری"/><input className={`${input} md:col-span-2`} defaultValue={a.notes} name="notes" placeholder="یادداشت"/><input className={input} defaultValue={variant?.displayOrder ?? 0} name="displayOrder" type="number" placeholder="ترتیب"/><label className="flex h-11 items-center gap-2 rounded-xl border border-[#cfb45f]/20 bg-[#031a13] px-3 text-sm text-[#d5c5a2]"><input defaultChecked={variant ? variant.isActive : true} name="isActive" type="checkbox"/>فعال</label>
</div>; }
export function AdminProductVariantManager({ productId, locale, variants, saved, archived, error }: { productId: string; locale: "fa"|"en"; variants: Variant[]; saved: boolean; archived: boolean; error?: string }) { return <section className="overflow-hidden rounded-[26px] border border-[#d0b359]/16 bg-[#041d15]/82">
  <header className="border-b border-[#d0b359]/12 px-5 py-5"><h2 className="flex items-center gap-2 font-semibold text-[#efd782]"><Boxes className="size-5"/>تنوع‌ها و موجودی مستقل</h2><p className="mt-1 text-xs leading-6 text-[#958a73]">SKU، رنگ، سایز، وزن، عیار، قیمت و موجودی هر مدل</p></header>
  <div className="space-y-5 p-4 sm:p-6">{saved ? <div className="rounded-xl border border-emerald-300/20 bg-emerald-950/20 p-3 text-sm text-emerald-100">تنوع‌ها ذخیره شدند.</div> : null}{archived ? <div className="rounded-xl border border-amber-300/20 bg-amber-950/20 p-3 text-sm text-amber-100">تنوع دارای سابقه سفارش بود و غیرفعال شد.</div> : null}{error ? <div className="rounded-xl border border-red-300/20 bg-red-950/20 p-3 text-sm text-red-100">{error}</div> : null}
    <form action={createAdminProductVariantAction.bind(null, productId, locale)} className="rounded-2xl border border-dashed border-[#d4b85f]/24 bg-black/10 p-4"><p className="mb-4 flex items-center gap-2 text-sm text-[#e2cc91]"><Plus className="size-4"/>تنوع جدید</p><Fields/><button className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-[linear-gradient(135deg,#a98a36,#e4c96f)] px-5 text-sm font-semibold text-[#10251c]"><Plus className="size-4"/>ساخت تنوع</button></form>
    {variants.map(v => <article key={v.id} className="rounded-2xl border border-[#d0b359]/14 bg-[#02150f]/74 p-4"><div className="mb-4 flex justify-between gap-3"><div><h3 className="text-[#e5d1a2]">{v.titleFa}</h3><p className="mt-1 text-xs text-[#887e69]">{v.sku || "بدون SKU"}</p></div><span className="text-xs text-[#cdbd9e]">{v.isActive ? "فعال" : "غیرفعال"}</span></div><form action={updateAdminProductVariantAction.bind(null, productId, v.id, locale)}><Fields variant={v}/><button className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl border border-[#d2b65e]/20 bg-[#d0b258]/8 px-5 text-sm text-[#e0c875]"><Save className="size-4"/>ذخیره</button></form><form action={deleteAdminProductVariantAction.bind(null, productId, v.id, locale)} className="mt-3 border-t border-[#d0b359]/10 pt-3"><button className="inline-flex h-10 items-center gap-2 rounded-xl border border-red-300/15 bg-red-950/15 px-5 text-sm text-red-200"><Trash2 className="size-4"/>حذف امن</button></form></article>)}
    {!variants.length ? <div className="grid min-h-28 place-items-center rounded-2xl border border-dashed border-[#d0b359]/18 text-sm text-[#91866f]">هنوز تنوعی ثبت نشده است.</div> : null}
  </div>
</section>; }
