import type { EloriaGuardian } from "@/lib/eloria-mythology";

type GuardianId = EloriaGuardian["id"];

export type CanonicalProductLegend = {
  key: string;
  nameFa: string;
  nameEn: string;
  titleFa: string;
  titleEn: string;
  age: number;
  guardianId: GuardianId;
  branchFa: string;
  branchEn: string;
  homelandFa: string;
  homelandEn: string;
  legendFa: string;
  legendEn: string;
  roleFa: string;
  roleEn: string;
  appearanceFa: string;
  clothingFa: string;
  accessoryFa: string;
};

const canonicalRoleEn =
  "She carries one piece of the mystery of the Shadow’s return; this legend drives her personal motive, and the associated jewel witnesses her moral choice.";

/**
 * The product-only subset of the official Eloria character bible.
 * Men and women aged 60+ remain canonical story characters, but must never be
 * assigned to products. This list is deliberately finite and non-generative.
 */
export const ELORIA_PRODUCT_LEGENDS: readonly CanonicalProductLegend[] = [
  {
    key: "character-01-01",
    nameFa: "آذرنوش",
    nameEn: "Azarnoosh",
    titleFa: "شنودگر دیوارها",
    titleEn: "Listener to Walls",
    age: 24,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "رواق پژواک، زیر باغ‌های خاموش ماه",
    homelandEn: "The Echo Arcade beneath the Silent Gardens of the Moon",
    legendFa: "سال‌ها صدایی از دیوار شرقی رواق می‌آمد و هرکس آن را می‌شنید، یکی از عزیزانش را فراموش می‌کرد. آذرنوش شبانه وارد دیوار شد و دریافت صدا، نامی دزدیده‌شده است؛ نام را در گره‌ای کور حبس کرد و خاطرات مردم بازگشت. همان نام، نخستین نشانه از دشمنی بود که روزی به درخت خاطره‌ها حمله کرد.",
    legendEn: "She heard a dreaming wall whisper the Shadow’s true name and trapped the voice inside a blind knot.",
    roleFa: "شنیدن رازهای پنهان در سنگ و بازگرداندن نام‌ها و خاطرات ربوده‌شده.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۴ ساله، صورت باریک، پوست زیتونی سرد، چشم مشکی نزدیک‌به‌هم، موی کوتاه پرکلاغی و قامت کوچک و چابک؛ پوست طبیعی با منافذ و موهای ظریف صورت.",
    clothingFa: "تونیک پشم زغالی با یقهٔ بلند و شلوار چرمی نرم؛ تار و پود و دوخت دستی اندکی نامنظم.",
    accessoryFa: "سنجاق مکرومهٔ مشکی با نقرهٔ اکسیدشده و اونیکس.",
  },
  {
    key: "character-01-02",
    nameFa: "مه‌دخت",
    nameEn: "Mahdokht",
    titleFa: "نگهبان فانوس‌های خاموش",
    titleEn: "Keeper of Silent Lanterns",
    age: 57,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "کوچهٔ فانوس‌های بی‌صدا",
    homelandEn: "The Alley of Soundless Lanterns",
    legendFa: "در کوچه‌ای که همه برای نجات خود دروغ می‌گفتند، مه‌دخت فانوسی ساخت که با هر دروغ خاموش می‌شد. او حقیقتی دردناک دربارهٔ خانواده‌اش را آشکار کرد و فانوس برای نخستین بار تا سپیده روشن ماند. نور آن بعدها راه یکی از هفت شاخهٔ شکستهٔ درخت خاطره‌ها را نشان داد.",
    legendEn: "She kept alight a lantern that went dark only whenever the Shadow lied.",
    roleFa: "سنجش حقیقت با فانوس‌های خاموش و راهنمایی کسانی که جرئت اعتراف دارند.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۵۷ ساله، صورت پهن با چروک‌های عمیق، پوست سبزه، یک چشم عسلی و یک چشم خاکستری و موی سفید بافته؛ بافت پوست کاملاً طبیعی.",
    clothingFa: "ردای کتان دودی و پیش‌بند چرمی سوخته با فرسودگی واقعی.",
    accessoryFa: "گردنبند مکرومهٔ خاکستری با نقره و چشم‌ببر.",
  },
  {
    key: "character-01-04",
    nameFa: "نوش‌آفرین",
    nameEn: "Noushafarin",
    titleFa: "بایگان نامه‌های بی‌نام",
    titleEn: "Archivist of Nameless Letters",
    age: 46,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "خانهٔ نامه‌های نرسیده",
    homelandEn: "The House of Undelivered Letters",
    legendFa: "نوش‌آفرین نامه‌ای بی‌امضا یافت که از وقوع آتشی در بایگانی خبر می‌داد و با دست‌خط سال‌های آیندهٔ خودش نوشته شده بود. میان نجات نامه‌ها و نجات شاگردش، شاگرد را برگزید؛ اما شاگرد همان شب نسخه‌ای از همه نامه‌ها تهیه کرده بود. در حاشیهٔ آخرین نامه، نشانی از بازگشت سایه باقی ماند.",
    legendEn: "She recognised an unsigned letter written in her own future handwriting.",
    roleFa: "حفاظت از نامه‌های بی‌نام و تشخیص پیام‌هایی که از آینده به گذشته می‌رسند.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۶ ساله، چهرهٔ کشیده، پوست روشن، چشم سبز تیره، مژهٔ کم‌پشت و موی مسی تیره؛ بافت طبیعی و بدون صافی دیجیتال.",
    clothingFa: "چادر-ردای بنفش دودی با آستر کاغذی و چین‌های تابع وزن.",
    accessoryFa: "انگشتر مکرومهٔ ابریشم بنفش با نقره و آمتیست.",
  },
  {
    key: "character-01-06",
    nameFa: "سروین",
    nameEn: "Sarvin",
    titleFa: "قفل‌ساز رازها",
    titleEn: "Locksmith of Secrets",
    age: 34,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "کارگاه قفل‌های بی‌کلید",
    homelandEn: "The Workshop of Keyless Locks",
    legendFa: "پادشاهی از سروین خواست خاطرهٔ خیانت برادرش را برای همیشه زندانی کند. سروین قفلی ساخت که هیچ کلیدی نداشت و تنها با بخشش گشوده می‌شد. سال‌ها بعد، پادشاه بخشید و از دل صندوق، تکه‌ای از پوست درخت خاطره‌ها بیرون آمد که سایه در پی آن بود.",
    legendEn: "She forged a lock no key can open; only the memory’s owner can release it through forgiveness.",
    roleFa: "ساخت قفل‌هایی برای رازهای خطرناک و گشودن آن‌ها فقط با رضایت صاحب خاطره.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۴ ساله، فک مربع، پوست گندمی، چشم قهوه‌ای روشن، موی بسیار کوتاه و دست‌های روغنی؛ پوست با ناهمگونی واقعی.",
    clothingFa: "جلیقهٔ چرمی زغالی بر پیراهن کتان با دوخت دستی.",
    accessoryFa: "کمربند مکرومهٔ سیاه با نقره و کلید فیروزه.",
  },
  {
    key: "character-02-01",
    nameFa: "روژان",
    nameEn: "Rozhan",
    titleFa: "معمار خواب‌های ناتمام",
    titleEn: "Architect of Unfinished Dreams",
    age: 27,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "ایوان ابرهای هفتم",
    homelandEn: "The Balcony of the Seventh Clouds",
    legendFa: "دختری بیمار آرزو داشت پیش از مرگ دریا را ببیند، اما راه همهٔ چشمه‌ها خشک شده بود. روژان برای او خوابی ساخت که مسیر آب‌های زیرزمین را آشکار کرد و مردم با دنبال‌کردن همان خواب، چشمه‌ها را نجات دادند. طرح رودهای خواب، درست شبیه یکی از ریشه‌های درخت خاطره‌ها بود.",
    legendEn: "For a girl who had never seen the sea, she built a dream that saved the path of the springs.",
    roleFa: "ساخت رویاهای راهنما برای کسانی که امیدشان را از دست داده‌اند.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۷ ساله، صورت بیضی، پوست روشن، چشم بنفش-خاکستری، موی بلوند تیرهٔ موج‌دار و اندام بلند؛ پوست طبیعی و چشم مرطوب.",
    clothingFa: "ردای ابریشم یاسی با چین‌های ابرگونه و تار و پود آشکار.",
    accessoryFa: "گردنبند مکرومهٔ سفید با نقره و آمتیست کم‌رنگ.",
  },
  {
    key: "character-02-04",
    nameFa: "کیانا",
    nameEn: "Kiana",
    titleFa: "بیداربان کودکان",
    titleEn: "Waker of Children",
    age: 17,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "تالار لالایی‌ها",
    homelandEn: "The Hall of Lullabies",
    legendFa: "صد کودک در خوابی مشترک گرفتار شدند و هر صبح نام یکی از آنان از یاد خانواده‌اش می‌رفت. کیانا لالایی ممنوعه را تا پایان خواند، با آنکه می‌دانست ممکن است صدای خود را از دست بدهد. کودکان بیدار شدند و آخرین نت آواز، هشداری دربارهٔ بازگشت سایه به همراه داشت.",
    legendEn: "She sang the forbidden lullaby and drew one hundred children out of the Shadow’s sleep.",
    roleFa: "بیدارکردن کودکان از رویاهای اسیرکننده و نگهبانی از لالایی‌های نجات‌بخش.",
    roleEn: canonicalRoleEn,
    appearanceFa: "دختر ۱۷ ساله، صورت گرد، پوست گندمی روشن، چشم عسلی درشت و موی مشکی دو بافت؛ چهره طبیعی و بدون روتوش پلاستیکی.",
    clothingFa: "پیراهن پنبه‌ای آبی روشن و شنل پرمانند با دوخت دستی.",
    accessoryFa: "گیرهٔ مکرومهٔ آبی با طلای زرد و مروارید.",
  },
  {
    key: "character-02-06",
    nameFa: "ترانه",
    nameEn: "Taraneh",
    titleFa: "جمع‌آورندهٔ خنده‌های گمشده",
    titleEn: "Collector of Lost Laughter",
    age: 22,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "بازارچهٔ آینه‌های خواب",
    homelandEn: "The Bazaar of Dream Mirrors",
    legendFa: "پس از مرگ ملکه، خنده از قصر ناپدید شد و چراغ مرکزی شهر خاموش ماند. ترانه خندهٔ گمشدهٔ ملکه را از ته چاهی بیرون آورد، اما آن را به شاه نفروخت و میان مردم تقسیم کرد. چراغ با شادی آزاد مردم روشن شد و نوری از شاخهٔ رویا در آن باقی ماند.",
    legendEn: "She lifted laughter from the bottom of a well and used it to light the palace lamp.",
    roleFa: "یافتن شادی‌های گمشده و بازگرداندن آن‌ها به صاحبان واقعی‌شان.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۲ ساله، صورت قلبی، پوست خرمایی، چشم سبز روشن و موهای مشکی فنری؛ منافذ و بافت طبیعی پوست.",
    clothingFa: "دامن چندلایهٔ فیروزه‌ای و جلیقهٔ ماه‌دوز.",
    accessoryFa: "خلخال مکرومهٔ فیروزه‌ای با نقره و توپاز.",
  },
  {
    key: "character-03-01",
    nameFa: "آرمیتا",
    nameEn: "Armita",
    titleFa: "کاتب پیمان نخستین",
    titleEn: "Scribe of the First Covenant",
    age: 39,
    guardianId: "atousa",
    branchFa: "میراث",
    branchEn: "Heritage",
    homelandFa: "تالار الواح مادران",
    homelandEn: "The Hall of the Mothers’ Tablets",
    legendFa: "آرمیتا هنگام مرمت پیمانی باستانی، بندی پاک‌شده را زیر نور انار دید: یکی از شاهدان، راه دشمن را خواهد گشود. او می‌توانست نام خائن را فاش کند، اما برای جلوگیری از مجازات یک بی‌گناه، فقط نشانه‌های انتخاب او را ثبت کرد. این سند بعدها بخشی گمشده از پیمان نخستین شناخته شد.",
    legendEn: "With pomegranate ink she restored a faded covenant clause that foretold a witness’s betrayal.",
    roleFa: "ثبت و تفسیر پیمان‌ها و جلوگیری از تحریف میراث تاریخی الوریا.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۹ ساله، صورت کشیده، پوست زیتونی، چشم عنبری و موی مشکی با رگهٔ سفید؛ بافت طبیعی پوست و لب.",
    clothingFa: "ردای زرشکی کتان و شال ترمه با دوخت دستی.",
    accessoryFa: "قلمدان مکرومهٔ زرشکی با طلا و عقیق.",
  },
  {
    key: "character-03-05",
    nameFa: "پرستو",
    nameEn: "Parastou",
    titleFa: "پژوهشگر تبارهای گمشده",
    titleEn: "Researcher of Lost Lineages",
    age: 30,
    guardianId: "atousa",
    branchFa: "میراث",
    branchEn: "Heritage",
    homelandFa: "آرشیو دودگرفتهٔ نسب‌ها",
    homelandEn: "The Smoke-Stained Archive of Lineages",
    legendFa: "پرستو در شجره‌نامه‌ای سوخته فهمید خانواده‌ای که همه خائن می‌پنداشتند، نسل‌ها نگهبان کودکی بی‌نام بوده‌اند. او حقیقت را منتشر کرد و آبروی از‌دست‌رفتهٔ آنان را بازگرداند. آخرین شاخهٔ شجره‌نامه نشان می‌داد سرنوشت یلدا و سایهٔ بی‌نام از گذشته‌ای مشترک جدا شده است.",
    legendEn: "In a burned family tree she discovered a blood bond between Yalda and the Shadow.",
    roleFa: "بازسازی تبارهای گمشده و پاک‌کردن اتهام‌های تاریخی با سند و حقیقت.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۰ ساله، صورت گرد، پوست روشن، چشم فندقی و موی قهوه‌ای با فر ریز؛ پوست با ناهمگونی طبیعی.",
    clothingFa: "قبای سبز تیره پر از جیب نسخه‌ها با چین‌های کاربردی.",
    accessoryFa: "دستبند مکرومهٔ زرشکی با نقره و گارنت.",
  },
  {
    key: "character-04-01",
    nameFa: "باران",
    nameEn: "Baran",
    titleFa: "شفادهندهٔ حافظهٔ آب",
    titleEn: "Healer of Water’s Memory",
    age: 33,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "درمانگاه آب‌های آوازخوان",
    homelandEn: "The Clinic of Singing Waters",
    legendFa: "رود شهر سیاه شد و درمانگران خواستند مسیرش را برای همیشه ببندند. باران به آب فرصت داد نخستین بارش خود را به یاد بیاورد؛ رود سرچشمهٔ پاکش را شناخت و زهر را از خود بیرون راند. در کف رود، برگی از درخت خاطره‌ها پیدا شد که حافظهٔ آب را حفظ کرده بود.",
    legendEn: "She made a poisoned river remember its first rain and heal itself.",
    roleFa: "درمان آب‌های آسیب‌دیده با بیدارکردن حافظهٔ طبیعی آن‌ها.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۳ ساله، چهرهٔ آرام، پوست قهوه‌ای روشن، چشم فیروزه‌ای و موی مشکی خیس‌نما؛ پوست طبیعی با رطوبت واقعی چشم.",
    clothingFa: "ردای حریر سبزآبی با پولک‌های قطره‌ای و چین‌های روان.",
    accessoryFa: "گردنبند مکرومهٔ آبی با نقره و آکوامارین.",
  },
  {
    key: "character-04-03",
    nameFa: "روشنک",
    nameEn: "Roshanak",
    titleFa: "قابلهٔ چشمه‌ها",
    titleEn: "Midwife of Springs",
    age: 52,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "غار زایش آب",
    homelandEn: "The Cave of Water’s Birth",
    legendFa: "وقتی خشکسالی آخرین روستا را خالی کرد، روشنک صدای آبی را شنید که زیر کوه گرفتار بود. سه شب سنگ را شکافت و چشمه‌ای تازه به دنیا آورد؛ نخستین جرعه، خاطرهٔ مادری را به کودک یتیمی بازگرداند. مردم گفتند آب از ریشه‌ای دورافتاده از درخت خاطره‌ها گذشته است.",
    legendEn: "As the land was dying, she delivered a spring whose water can reclaim one memory from death.",
    roleFa: "یافتن و آزادکردن چشمه‌های نوزاد و رساندن آب به سرزمین‌های رو به مرگ.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۵۲ ساله، صورت پهن، پوست سبزه، چشم مشکی، موی خاکستری پیچیده و دستان قوی؛ پوست با منافذ و ناهمگونی طبیعی.",
    clothingFa: "جامهٔ سفید و شال آبی سیر با دوخت دستی.",
    accessoryFa: "بازوبند مکرومهٔ سفید با نقره و مروارید.",
  },
  {
    key: "character-04-05",
    nameFa: "لاله‌رخ",
    nameEn: "Lalehrokh",
    titleFa: "نگهبان بذر آخر",
    titleEn: "Keeper of the Last Seed",
    age: 20,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "گلخانهٔ نفس سبز",
    homelandEn: "The Green Breath Conservatory",
    legendFa: "در یورش سپاه فراموشی، تنها بذر انار خاطره باقی مانده بود. لاله‌رخ برای پنهان‌کردنش بذر را بلعید و پذیرفت تا بهار بعد هیچ‌کس نام او را به یاد نیاورد. وقتی بذر دوباره جوانه زد، نام لاله‌رخ و یکی از هفت خاطرهٔ شکسته با هم به جهان بازگشتند.",
    legendEn: "She swallowed the last seed of the Memory Pomegranate to hide it from the Shadow.",
    roleFa: "نگهداری بذرهای کمیاب و احیای باغ‌هایی که حافظه و زندگی‌شان نابود شده است.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۰ ساله، صورت ظریف، پوست روشن با کک‌ومک، چشم قهوه‌ای و موی سرخ‌قهوه‌ای؛ بافت پوست و کک‌ومک کاملاً طبیعی.",
    clothingFa: "پیراهن سبز روشن با جیب‌های بذر و تار و پود آشکار.",
    accessoryFa: "کیسهٔ مکرومهٔ کرم با طلا و زبرجد.",
  },
  {
    key: "character-05-01",
    nameFa: "گره‌ناز",
    nameEn: "Gerehnaz",
    titleFa: "استاد گره‌های حافظه",
    titleEn: "Master of Memory Knots",
    age: 29,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "کارگاه گره‌های هزارلایه",
    homelandEn: "The Workshop of Thousand-Layered Knots",
    legendFa: "پیش از آنکه سیلاب شهر را ببرد، گره‌ناز از هر خانه یک خاطره گرفت و همه را در رشته‌ای باریک بافت. پس از فروکش‌کردن آب، مردم با لمس همان رشته نام کوچه‌ها و عزیزانشان را به یاد آوردند. الگوی هفت‌گانهٔ بافت، نقشهٔ شاخه‌های درخت خاطره‌ها را پنهان کرده بود.",
    legendEn: "She tied a knot that held an entire city’s memory inside a hair-thin thread.",
    roleFa: "بافتن حافظهٔ جمعی در گره‌ها و بازگرداندن هویت به شهرهای ویران‌شده.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۹ ساله، صورت مربعی، پوست گندمی، چشم مشکی، موی ضخیم دو بافت و انگشتان بلند؛ پوست طبیعی و بدون روتوش.",
    clothingFa: "جامهٔ کتان نخودی و جلیقهٔ خردلی با دوخت اندکی نامنظم.",
    accessoryFa: "گردنبند مکرومهٔ پیچیدهٔ طلایی با طلا و سیترین.",
  },
  {
    key: "character-05-03",
    nameFa: "ساغر",
    nameEn: "Saghar",
    titleFa: "رنگرز سپیده",
    titleEn: "Dyer of Dawn",
    age: 43,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "حوضخانهٔ رنگ‌های زنده",
    homelandEn: "The Cistern Hall of Living Colours",
    legendFa: "تاریکی سه ماه بر روستا ماند و رنگ‌ها یکی‌یکی از لباس مردم محو شدند. ساغر پیش از طلوع به بلندترین بام رفت، رنگ سپیده را قرض گرفت و پارچه‌ای بافت که نخستین نور را به خانه‌ها بازتاب می‌داد. در حاشیهٔ پارچه، نشان شاخهٔ هنر از درخت خاطره‌ها پدیدار شد.",
    legendEn: "She borrowed dawn’s colour from the sky and wove a cloth that repels darkness.",
    roleFa: "ساخت رنگ‌های زنده از نور طبیعت و بازگرداندن امید به مکان‌های خاموش.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۳ ساله، صورت بیضی، پوست خرمایی، چشم آبی و موی مشکی زیر سربند رنگی؛ پوست با منافذ واقعی.",
    clothingFa: "پیراهن سفید لکه‌دار و دامن لاجوردی با فرسودگی متناسب با رنگرزی.",
    accessoryFa: "گوشوارهٔ مکرومهٔ چندرنگ با نقره و اوپال آتشی.",
  },
  {
    key: "character-05-05",
    nameFa: "نیلا",
    nameEn: "Nila",
    titleFa: "بافندهٔ نقشه‌های پوشیدنی",
    titleEn: "Weaver of Wearable Maps",
    age: 18,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "اتاق دارهای معلق",
    homelandEn: "The Chamber of Suspended Looms",
    legendFa: "نیلا فهمید نقشه‌های کاغذی قلمروها شبانه تغییر می‌کنند و مسافران را به بیراهه می‌برند. او مسیر درست را در آستر شنلی بافت که نوشته‌هایش فقط در باد آشکار می‌شد. هفت مسیر نهایی در مرکز نقشه به جای زخم درخت خاطره‌ها می‌رسیدند.",
    legendEn: "She wove the seven realms’ map into a cloak lining readable only in Raha’s wind.",
    roleFa: "بافتن نقشه‌های پوشیدنی برای هدایت مسافران میان قلمروهای متغیر.",
    roleEn: canonicalRoleEn,
    appearanceFa: "دختر ۱۸ ساله، صورت کشیده، پوست تیره، چشم کهربایی و موهای کوتاه فر؛ بافت طبیعی پوست و مو.",
    clothingFa: "تونیک آبی و شلوار راحت کارگاهی با چین‌های تابع حرکت.",
    accessoryFa: "کمربند مکرومهٔ لاجوردی با طلا و سودالیت.",
  },
  {
    key: "character-06-01",
    nameFa: "فرنوش",
    nameEn: "Farnoosh",
    titleFa: "رمزگشای کتاب ممنوعه",
    titleEn: "Decoder of the Forbidden Book",
    age: 36,
    guardianId: "vista",
    branchFa: "خرد",
    branchEn: "Wisdom",
    homelandFa: "مخزن کتاب‌های زنجیرشده",
    homelandEn: "The Vault of Chained Books",
    legendFa: "کتابی ممنوعه هر شب یکی از صفحه‌هایش را می‌سوزاند تا راز آخرش خوانده نشود. فرنوش تا سپیده رمزها را گشود و فهمید هیولایی که همه سایه می‌نامند، زمانی انسانی صاحب نام و قلب بوده است. او صفحه را نابود نکرد؛ زیرا باور داشت شناخت گذشته تنها راه شکست‌دادن دشمن در آینده است.",
    legendEn: "She read a page proving that the Shadow once possessed a name and a heart.",
    roleFa: "رمزگشایی متون ممنوعه و جداکردن حقیقت تاریخی از افسانه و ترس.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۶ ساله، صورت مثلثی، پوست زیتونی، چشم طلایی و موی مشکی صاف تا چانه؛ پوست طبیعی و چشم با شکست نور واقعی.",
    clothingFa: "قبای سرمه‌ای با یقهٔ هندسی و دوخت دستی.",
    accessoryFa: "تک‌چشم مکرومهٔ آبی با نقره و کوارتز دودی.",
  },
  {
    key: "character-06-05",
    nameFa: "سپیده",
    nameEn: "Sepideh",
    titleFa: "کتابدار صداهای خاموش",
    titleEn: "Librarian of Silent Voices",
    age: 25,
    guardianId: "vista",
    branchFa: "خرد",
    branchEn: "Wisdom",
    homelandFa: "تالار کتاب‌های بی‌جوهر",
    homelandEn: "The Hall of Inkless Books",
    legendFa: "در کتابخانهٔ نور، کتابی بود که هیچ حرفی نداشت اما شب‌ها گریه می‌کرد. سپیده آموخت سکوت میان صفحه‌ها را بخواند و صدای آخرین نگهبان نخستین را شنید که محل یک خاطرهٔ نجات‌بخش را می‌گفت. او صدا را ثبت نکرد تا به دست دشمن نیفتد و خودش حافظ زندهٔ پیام شد.",
    legendEn: "She found the First Keeper’s final voice among pages without words.",
    roleFa: "شنیدن دانش پنهان در سکوت و نگهداری پیام‌هایی که نباید نوشته شوند.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۵ ساله، صورت باریک، پوست گندمی روشن، چشم مشکی و موی قهوه‌ای با چتری صاف؛ بافت طبیعی پوست و مژه.",
    clothingFa: "پیراهن سرمه‌ای ساده و دستکش سفید با تار و پود آشکار.",
    accessoryFa: "گوشوارهٔ مکرومهٔ سفید با طلا و مروارید سیاه.",
  },
  {
    key: "character-07-01",
    nameFa: "آوا",
    nameEn: "Ava",
    titleFa: "پیک گذرگاه باد",
    titleEn: "Courier of the Wind Passage",
    age: 23,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "پل‌های پارچه‌ای باد",
    homelandEn: "The Wind’s Fabric Bridges",
    legendFa: "توفانی میان دو شهر برخاست که واژه‌ها را از ذهن هر پیک می‌دزدید. آوا پیام صلح را نه با کلمات، بلکه با ضرب‌آهنگ قدم‌ها و گره‌های دستبندش حمل کرد و جنگ را پیش از آغاز متوقف ساخت. یکی از گره‌ها نشان می‌داد باد، هنوز فرمان پیمان نخستین را به یاد دارد.",
    legendEn: "She carried a message through a storm that stole every word from couriers’ minds.",
    roleFa: "رساندن پیام‌های حیاتی از مسیرهایی که زبان، حافظه یا راه در آن‌ها از کار می‌افتد.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۳ ساله، صورت بیضی، پوست برنزه، چشم سبز، موهای مشکی کوتاه و پریشان و اندام دونده؛ آفتاب‌خوردگی طبیعی.",
    clothingFa: "کت لاجوردی کوتاه و شلوار کرم با چین‌های تابع حرکت.",
    accessoryFa: "خلخال مکرومهٔ آبی با نقره و فیروزه.",
  },
  {
    key: "character-07-03",
    nameFa: "شهرزاد",
    nameEn: "Shahrzad",
    titleFa: "قصه‌گوی کاروان‌های آزاد",
    titleEn: "Storyteller of Free Caravans",
    age: 48,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "کاروانسرای هزارپنجره",
    homelandEn: "The Caravanserai of a Thousand Windows",
    legendFa: "راهزنان کاروانی را با زنجیرهایی بستند که فقط با اعتراف اسیران محکم‌تر می‌شد. شهرزاد داستان هر مسافر را چنان روایت کرد که آنان دوباره ارزش و اختیار خود را به یاد آوردند؛ زنجیرها بی‌کلید فرو ریختند. پایان قصه از پرنده‌ای می‌گفت که خبر شکستن شاخهٔ آزادی را به هفت نگهبان رساند.",
    legendEn: "She told a story that opened an imprisoned caravan’s bonds without a key.",
    roleFa: "آزادکردن انسان‌ها با روایت حقیقت زندگی‌شان و حفظ داستان کاروان‌های بی‌صدا.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۸ ساله، صورت گرد، پوست خرمایی، چشم کهربایی و موی مشکی-نقره‌ای پرحجم؛ چهره با بافت طبیعی و موهای ظریف.",
    clothingFa: "ردای نارنجی سوخته و شال آبی با دوخت دستی.",
    accessoryFa: "گردنبند مکرومهٔ نارنجی با طلا و کارنلین.",
  },
  {
    key: "character-07-05",
    nameFa: "یگانه",
    nameEn: "Yeganeh",
    titleFa: "نگهبان درهای انتخاب",
    titleEn: "Keeper of the Doors of Choice",
    age: 31,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "میدان هفت در",
    homelandEn: "The Square of Seven Doors",
    legendFa: "یگانه نگهبان دری بود که می‌توانست دشمن زخمی را برای همیشه بیرون نگه دارد. برخلاف فرمان شهر، در را گشود و حق انتخاب را به او سپرد؛ دشمن سلاحش را زمین گذاشت و جان کودکی را نجات داد. همان در بعدها یکی از راه‌های هفت نگهبان به سوی درخت خاطره‌ها شد.",
    legendEn: "She left a door open for an enemy, knowing only a free choice could change them.",
    roleFa: "حفاظت از حق انتخاب و گشودن درهایی که تنها با تصمیم آزاد انسان معنا پیدا می‌کنند.",
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۱ ساله، چهرهٔ نامتقارن جذاب، پوست زیتونی، یک چشم سبز و یک چشم قهوه‌ای و موی مسی کوتاه؛ پوست بدون صافی دیجیتال.",
    clothingFa: "قبای دورنگ آبی و خاکستری با چین‌های طبیعی.",
    accessoryFa: "گوشوارهٔ مکرومهٔ دوگانه با طلا و الکساندریت.",
  },
] as const;
