import type { EloriaGuardian } from "@/lib/eloria-mythology";

type GuardianId = EloriaGuardian["id"];

export type CanonicalProductLegend = {
  key: string;
  nameFa: string;
  nameEn: string;
  titleFa: string;
  titleEn: string;
  age: number;
  guardianId: GuardianId;
  branchFa: string;
  branchEn: string;
  homelandFa: string;
  homelandEn: string;
  legendFa: string;
  legendEn: string;
  roleFa: string;
  roleEn: string;
  appearanceFa: string;
  clothingFa: string;
  accessoryFa: string;
};

const canonicalRoleFa =
  "حامل یک قطعه از معمای بازگشت سایه؛ انگیزهٔ شخصی او از همین افسانه ناشی می‌شود و محصول مرتبط، شاهد فیزیکی انتخاب اخلاقی اوست.";
const canonicalRoleEn =
  "She carries one piece of the mystery of the Shadow’s return; this legend drives her personal motive, and the associated jewel witnesses her moral choice.";

/**
 * The product-only subset of the official Eloria character bible.
 * Men and women aged 60+ remain canonical story characters, but must never be
 * assigned to products. This list is deliberately finite and non-generative.
 */
export const ELORIA_PRODUCT_LEGENDS: readonly CanonicalProductLegend[] = [
  {
    key: "character-01-01",
    nameFa: "آذرنوش",
    nameEn: "Azarnoosh",
    titleFa: "شنودگر دیوارها",
    titleEn: "Listener to Walls",
    age: 24,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "رواق پژواک، زیر باغ‌های خاموش ماه",
    homelandEn: "The Echo Arcade beneath the Silent Gardens of the Moon",
    legendFa: "شنید دیواری در خواب نام واقعی سایه را زمزمه می‌کند و آن صدا را در گره‌ای کور حبس کرد.",
    legendEn: "She heard a dreaming wall whisper the Shadow’s true name and trapped the voice inside a blind knot.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۴ ساله، صورت باریک، پوست زیتونی سرد، چشم مشکی نزدیک‌به‌هم، موی کوتاه پرکلاغی و قامت کوچک و چابک؛ پوست طبیعی با منافذ و موهای ظریف صورت.",
    clothingFa: "تونیک پشم زغالی با یقهٔ بلند و شلوار چرمی نرم؛ تار و پود و دوخت دستی اندکی نامنظم.",
    accessoryFa: "سنجاق مکرومهٔ مشکی با نقرهٔ اکسیدشده و اونیکس.",
  },
  {
    key: "character-01-02",
    nameFa: "مه‌دخت",
    nameEn: "Mahdokht",
    titleFa: "نگهبان فانوس‌های خاموش",
    titleEn: "Keeper of Silent Lanterns",
    age: 57,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "کوچهٔ فانوس‌های بی‌صدا",
    homelandEn: "The Alley of Soundless Lanterns",
    legendFa: "فانوسی را روشن نگه داشت که تنها هنگام دروغ‌گفتن سایه خاموش می‌شد.",
    legendEn: "She kept alight a lantern that went dark only whenever the Shadow lied.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۵۷ ساله، صورت پهن با چروک‌های عمیق، پوست سبزه، یک چشم عسلی و یک چشم خاکستری و موی سفید بافته؛ بافت پوست کاملاً طبیعی.",
    clothingFa: "ردای کتان دودی و پیش‌بند چرمی سوخته با فرسودگی واقعی.",
    accessoryFa: "گردنبند مکرومهٔ خاکستری با نقره و چشم‌ببر.",
  },
  {
    key: "character-01-04",
    nameFa: "نوش‌آفرین",
    nameEn: "Noushafarin",
    titleFa: "بایگان نامه‌های بی‌نام",
    titleEn: "Archivist of Nameless Letters",
    age: 46,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "خانهٔ نامه‌های نرسیده",
    homelandEn: "The House of Undelivered Letters",
    legendFa: "نامه‌ای بی‌امضا را شناخت که با دست‌خط آیندهٔ خودش نوشته شده بود.",
    legendEn: "She recognised an unsigned letter written in her own future handwriting.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۶ ساله، چهرهٔ کشیده، پوست روشن، چشم سبز تیره، مژهٔ کم‌پشت و موی مسی تیره؛ بافت طبیعی و بدون صافی دیجیتال.",
    clothingFa: "چادر-ردای بنفش دودی با آستر کاغذی و چین‌های تابع وزن.",
    accessoryFa: "انگشتر مکرومهٔ ابریشم بنفش با نقره و آمتیست.",
  },
  {
    key: "character-01-06",
    nameFa: "سروین",
    nameEn: "Sarvin",
    titleFa: "قفل‌ساز رازها",
    titleEn: "Locksmith of Secrets",
    age: 34,
    guardianId: "yalda",
    branchFa: "راز",
    branchEn: "Mystery",
    homelandFa: "کارگاه قفل‌های بی‌کلید",
    homelandEn: "The Workshop of Keyless Locks",
    legendFa: "قفلی ساخت که با کلید باز نمی‌شود؛ فقط صاحب خاطره می‌تواند آن را ببخشد.",
    legendEn: "She forged a lock no key can open; only the memory’s owner can release it through forgiveness.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۴ ساله، فک مربع، پوست گندمی، چشم قهوه‌ای روشن، موی بسیار کوتاه و دست‌های روغنی؛ پوست با ناهمگونی واقعی.",
    clothingFa: "جلیقهٔ چرمی زغالی بر پیراهن کتان با دوخت دستی.",
    accessoryFa: "کمربند مکرومهٔ سیاه با نقره و کلید فیروزه.",
  },
  {
    key: "character-02-01",
    nameFa: "روژان",
    nameEn: "Rozhan",
    titleFa: "معمار خواب‌های ناتمام",
    titleEn: "Architect of Unfinished Dreams",
    age: 27,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "ایوان ابرهای هفتم",
    homelandEn: "The Balcony of the Seventh Clouds",
    legendFa: "برای دختری که هرگز دریا ندیده بود خوابی ساخت که راه چشمه‌ها را نجات داد.",
    legendEn: "For a girl who had never seen the sea, she built a dream that saved the path of the springs.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۷ ساله، صورت بیضی، پوست روشن، چشم بنفش-خاکستری، موی بلوند تیرهٔ موج‌دار و اندام بلند؛ پوست طبیعی و چشم مرطوب.",
    clothingFa: "ردای ابریشم یاسی با چین‌های ابرگونه و تار و پود آشکار.",
    accessoryFa: "گردنبند مکرومهٔ سفید با نقره و آمتیست کم‌رنگ.",
  },
  {
    key: "character-02-04",
    nameFa: "کیانا",
    nameEn: "Kiana",
    titleFa: "بیداربان کودکان",
    titleEn: "Waker of Children",
    age: 17,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "تالار لالایی‌ها",
    homelandEn: "The Hall of Lullabies",
    legendFa: "لالایی ممنوعه را خواند و صد کودک را از خواب سایه بیرون آورد.",
    legendEn: "She sang the forbidden lullaby and drew one hundred children out of the Shadow’s sleep.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "دختر ۱۷ ساله، صورت گرد، پوست گندمی روشن، چشم عسلی درشت و موی مشکی دو بافت؛ چهره طبیعی و بدون روتوش پلاستیکی.",
    clothingFa: "پیراهن پنبه‌ای آبی روشن و شنل پرمانند با دوخت دستی.",
    accessoryFa: "گیرهٔ مکرومهٔ آبی با طلای زرد و مروارید.",
  },
  {
    key: "character-02-06",
    nameFa: "ترانه",
    nameEn: "Taraneh",
    titleFa: "جمع‌آورندهٔ خنده‌های گمشده",
    titleEn: "Collector of Lost Laughter",
    age: 22,
    guardianId: "mahora",
    branchFa: "رویا",
    branchEn: "Dream",
    homelandFa: "بازارچهٔ آینه‌های خواب",
    homelandEn: "The Bazaar of Dream Mirrors",
    legendFa: "خنده‌ای را از ته چاهی بیرون آورد و با آن چراغ قصر را روشن کرد.",
    legendEn: "She lifted laughter from the bottom of a well and used it to light the palace lamp.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۲ ساله، صورت قلبی، پوست خرمایی، چشم سبز روشن و موهای مشکی فنری؛ منافذ و بافت طبیعی پوست.",
    clothingFa: "دامن چندلایهٔ فیروزه‌ای و جلیقهٔ ماه‌دوز.",
    accessoryFa: "خلخال مکرومهٔ فیروزه‌ای با نقره و توپاز.",
  },
  {
    key: "character-03-01",
    nameFa: "آرمیتا",
    nameEn: "Armita",
    titleFa: "کاتب پیمان نخستین",
    titleEn: "Scribe of the First Covenant",
    age: 39,
    guardianId: "atousa",
    branchFa: "میراث",
    branchEn: "Heritage",
    homelandFa: "تالار الواح مادران",
    homelandEn: "The Hall of the Mothers’ Tablets",
    legendFa: "بندی محوشده از پیمان را با جوهر انار بازنوشت؛ بندی که خیانت یکی از شاهدان را پیش‌بینی می‌کرد.",
    legendEn: "With pomegranate ink she restored a faded covenant clause that foretold a witness’s betrayal.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۹ ساله، صورت کشیده، پوست زیتونی، چشم عنبری و موی مشکی با رگهٔ سفید؛ بافت طبیعی پوست و لب.",
    clothingFa: "ردای زرشکی کتان و شال ترمه با دوخت دستی.",
    accessoryFa: "قلمدان مکرومهٔ زرشکی با طلا و عقیق.",
  },
  {
    key: "character-03-05",
    nameFa: "پرستو",
    nameEn: "Parastou",
    titleFa: "پژوهشگر تبارهای گمشده",
    titleEn: "Researcher of Lost Lineages",
    age: 30,
    guardianId: "atousa",
    branchFa: "میراث",
    branchEn: "Heritage",
    homelandFa: "آرشیو دودگرفتهٔ نسب‌ها",
    homelandEn: "The Smoke-Stained Archive of Lineages",
    legendFa: "در شجره‌نامه‌ای سوخته پیوند خونی یلدا و سایه را کشف کرد.",
    legendEn: "In a burned family tree she discovered a blood bond between Yalda and the Shadow.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۰ ساله، صورت گرد، پوست روشن، چشم فندقی و موی قهوه‌ای با فر ریز؛ پوست با ناهمگونی طبیعی.",
    clothingFa: "قبای سبز تیره پر از جیب نسخه‌ها با چین‌های کاربردی.",
    accessoryFa: "دستبند مکرومهٔ زرشکی با نقره و گارنت.",
  },
  {
    key: "character-04-01",
    nameFa: "باران",
    nameEn: "Baran",
    titleFa: "شفادهندهٔ حافظهٔ آب",
    titleEn: "Healer of Water’s Memory",
    age: 33,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "درمانگاه آب‌های آوازخوان",
    homelandEn: "The Clinic of Singing Waters",
    legendFa: "رودی مسموم را واداشت نخستین بارانش را به یاد بیاورد و خود را درمان کند.",
    legendEn: "She made a poisoned river remember its first rain and heal itself.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۳ ساله، چهرهٔ آرام، پوست قهوه‌ای روشن، چشم فیروزه‌ای و موی مشکی خیس‌نما؛ پوست طبیعی با رطوبت واقعی چشم.",
    clothingFa: "ردای حریر سبزآبی با پولک‌های قطره‌ای و چین‌های روان.",
    accessoryFa: "گردنبند مکرومهٔ آبی با نقره و آکوامارین.",
  },
  {
    key: "character-04-03",
    nameFa: "روشنک",
    nameEn: "Roshanak",
    titleFa: "قابلهٔ چشمه‌ها",
    titleEn: "Midwife of Springs",
    age: 52,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "غار زایش آب",
    homelandEn: "The Cave of Water’s Birth",
    legendFa: "چشمه‌ای را هنگام مرگ زمین به دنیا آورد؛ آب آن یک خاطره را از مرگ پس می‌گیرد.",
    legendEn: "As the land was dying, she delivered a spring whose water can reclaim one memory from death.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۵۲ ساله، صورت پهن، پوست سبزه، چشم مشکی، موی خاکستری پیچیده و دستان قوی؛ پوست با منافذ و ناهمگونی طبیعی.",
    clothingFa: "جامهٔ سفید و شال آبی سیر با دوخت دستی.",
    accessoryFa: "بازوبند مکرومهٔ سفید با نقره و مروارید.",
  },
  {
    key: "character-04-05",
    nameFa: "لاله‌رخ",
    nameEn: "Lalehrokh",
    titleFa: "نگهبان بذر آخر",
    titleEn: "Keeper of the Last Seed",
    age: 20,
    guardianId: "anahid",
    branchFa: "زندگی",
    branchEn: "Life",
    homelandFa: "گلخانهٔ نفس سبز",
    homelandEn: "The Green Breath Conservatory",
    legendFa: "آخرین بذر انار خاطره را بلعید تا از دست سایه پنهانش کند.",
    legendEn: "She swallowed the last seed of the Memory Pomegranate to hide it from the Shadow.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۰ ساله، صورت ظریف، پوست روشن با کک‌ومک، چشم قهوه‌ای و موی سرخ‌قهوه‌ای؛ بافت پوست و کک‌ومک کاملاً طبیعی.",
    clothingFa: "پیراهن سبز روشن با جیب‌های بذر و تار و پود آشکار.",
    accessoryFa: "کیسهٔ مکرومهٔ کرم با طلا و زبرجد.",
  },
  {
    key: "character-05-01",
    nameFa: "گره‌ناز",
    nameEn: "Gerehnaz",
    titleFa: "استاد گره‌های حافظه",
    titleEn: "Master of Memory Knots",
    age: 29,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "کارگاه گره‌های هزارلایه",
    homelandEn: "The Workshop of Thousand-Layered Knots",
    legendFa: "گرهی زد که خاطرهٔ یک شهر کامل را در رشته‌ای به اندازهٔ مو نگه داشت.",
    legendEn: "She tied a knot that held an entire city’s memory inside a hair-thin thread.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۹ ساله، صورت مربعی، پوست گندمی، چشم مشکی، موی ضخیم دو بافت و انگشتان بلند؛ پوست طبیعی و بدون روتوش.",
    clothingFa: "جامهٔ کتان نخودی و جلیقهٔ خردلی با دوخت اندکی نامنظم.",
    accessoryFa: "گردنبند مکرومهٔ پیچیدهٔ طلایی با طلا و سیترین.",
  },
  {
    key: "character-05-03",
    nameFa: "ساغر",
    nameEn: "Saghar",
    titleFa: "رنگرز سپیده",
    titleEn: "Dyer of Dawn",
    age: 43,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "حوضخانهٔ رنگ‌های زنده",
    homelandEn: "The Cistern Hall of Living Colours",
    legendFa: "رنگ سپیده را از آسمان قرض گرفت و پارچه‌ای بافت که تاریکی را پس می‌زند.",
    legendEn: "She borrowed dawn’s colour from the sky and wove a cloth that repels darkness.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۳ ساله، صورت بیضی، پوست خرمایی، چشم آبی و موی مشکی زیر سربند رنگی؛ پوست با منافذ واقعی.",
    clothingFa: "پیراهن سفید لکه‌دار و دامن لاجوردی با فرسودگی متناسب با رنگرزی.",
    accessoryFa: "گوشوارهٔ مکرومهٔ چندرنگ با نقره و اوپال آتشی.",
  },
  {
    key: "character-05-05",
    nameFa: "نیلا",
    nameEn: "Nila",
    titleFa: "بافندهٔ نقشه‌های پوشیدنی",
    titleEn: "Weaver of Wearable Maps",
    age: 18,
    guardianId: "parnia",
    branchFa: "هنر",
    branchEn: "Craft",
    homelandFa: "اتاق دارهای معلق",
    homelandEn: "The Chamber of Suspended Looms",
    legendFa: "نقشهٔ هفت قلمرو را در آستر شنلی بافت که فقط در باد رها خوانده می‌شود.",
    legendEn: "She wove the seven realms’ map into a cloak lining readable only in Raha’s wind.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "دختر ۱۸ ساله، صورت کشیده، پوست تیره، چشم کهربایی و موهای کوتاه فر؛ بافت طبیعی پوست و مو.",
    clothingFa: "تونیک آبی و شلوار راحت کارگاهی با چین‌های تابع حرکت.",
    accessoryFa: "کمربند مکرومهٔ لاجوردی با طلا و سودالیت.",
  },
  {
    key: "character-06-01",
    nameFa: "فرنوش",
    nameEn: "Farnoosh",
    titleFa: "رمزگشای کتاب ممنوعه",
    titleEn: "Decoder of the Forbidden Book",
    age: 36,
    guardianId: "vista",
    branchFa: "خرد",
    branchEn: "Wisdom",
    homelandFa: "مخزن کتاب‌های زنجیرشده",
    homelandEn: "The Vault of Chained Books",
    legendFa: "صفحه‌ای را خواند که ثابت می‌کرد سایه زمانی نام و قلب داشته است.",
    legendEn: "She read a page proving that the Shadow once possessed a name and a heart.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۶ ساله، صورت مثلثی، پوست زیتونی، چشم طلایی و موی مشکی صاف تا چانه؛ پوست طبیعی و چشم با شکست نور واقعی.",
    clothingFa: "قبای سرمه‌ای با یقهٔ هندسی و دوخت دستی.",
    accessoryFa: "تک‌چشم مکرومهٔ آبی با نقره و کوارتز دودی.",
  },
  {
    key: "character-06-05",
    nameFa: "سپیده",
    nameEn: "Sepideh",
    titleFa: "کتابدار صداهای خاموش",
    titleEn: "Librarian of Silent Voices",
    age: 25,
    guardianId: "vista",
    branchFa: "خرد",
    branchEn: "Wisdom",
    homelandFa: "تالار کتاب‌های بی‌جوهر",
    homelandEn: "The Hall of Inkless Books",
    legendFa: "صدای آخرین نگهبان نخستین را میان صفحات بی‌حرف پیدا کرد.",
    legendEn: "She found the First Keeper’s final voice among pages without words.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۵ ساله، صورت باریک، پوست گندمی روشن، چشم مشکی و موی قهوه‌ای با چتری صاف؛ بافت طبیعی پوست و مژه.",
    clothingFa: "پیراهن سرمه‌ای ساده و دستکش سفید با تار و پود آشکار.",
    accessoryFa: "گوشوارهٔ مکرومهٔ سفید با طلا و مروارید سیاه.",
  },
  {
    key: "character-07-01",
    nameFa: "آوا",
    nameEn: "Ava",
    titleFa: "پیک گذرگاه باد",
    titleEn: "Courier of the Wind Passage",
    age: 23,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "پل‌های پارچه‌ای باد",
    homelandEn: "The Wind’s Fabric Bridges",
    legendFa: "پیامی را از میان توفانی برد که هر واژه را از ذهن پیک‌ها می‌دزدید.",
    legendEn: "She carried a message through a storm that stole every word from couriers’ minds.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۲۳ ساله، صورت بیضی، پوست برنزه، چشم سبز، موهای مشکی کوتاه و پریشان و اندام دونده؛ آفتاب‌خوردگی طبیعی.",
    clothingFa: "کت لاجوردی کوتاه و شلوار کرم با چین‌های تابع حرکت.",
    accessoryFa: "خلخال مکرومهٔ آبی با نقره و فیروزه.",
  },
  {
    key: "character-07-03",
    nameFa: "شهرزاد",
    nameEn: "Shahrzad",
    titleFa: "قصه‌گوی کاروان‌های آزاد",
    titleEn: "Storyteller of Free Caravans",
    age: 48,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "کاروانسرای هزارپنجره",
    homelandEn: "The Caravanserai of a Thousand Windows",
    legendFa: "قصه‌ای گفت که بندهای یک کاروان اسیر را بی‌کلید گشود.",
    legendEn: "She told a story that opened an imprisoned caravan’s bonds without a key.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۴۸ ساله، صورت گرد، پوست خرمایی، چشم کهربایی و موی مشکی-نقره‌ای پرحجم؛ چهره با بافت طبیعی و موهای ظریف.",
    clothingFa: "ردای نارنجی سوخته و شال آبی با دوخت دستی.",
    accessoryFa: "گردنبند مکرومهٔ نارنجی با طلا و کارنلین.",
  },
  {
    key: "character-07-05",
    nameFa: "یگانه",
    nameEn: "Yeganeh",
    titleFa: "نگهبان درهای انتخاب",
    titleEn: "Keeper of the Doors of Choice",
    age: 31,
    guardianId: "raha",
    branchFa: "آزادی",
    branchEn: "Freedom",
    homelandFa: "میدان هفت در",
    homelandEn: "The Square of Seven Doors",
    legendFa: "دری را برای دشمن باز گذاشت چون می‌دانست تنها انتخاب آزاد او را تغییر می‌دهد.",
    legendEn: "She left a door open for an enemy, knowing only a free choice could change them.",
    roleFa: canonicalRoleFa,
    roleEn: canonicalRoleEn,
    appearanceFa: "زن ۳۱ ساله، چهرهٔ نامتقارن جذاب، پوست زیتونی، یک چشم سبز و یک چشم قهوه‌ای و موی مسی کوتاه؛ پوست بدون صافی دیجیتال.",
    clothingFa: "قبای دورنگ آبی و خاکستری با چین‌های طبیعی.",
    accessoryFa: "گوشوارهٔ مکرومهٔ دوگانه با طلا و الکساندریت.",
  },
] as const;

