import { PackageCheck, Save, Truck } from "lucide-react";
import { saveAdminShipmentAction, transitionAdminOrderAction } from "@/app/[locale]/admin/(protected)/orders/actions";
import { availableAdminTransitions } from "@/lib/order-operations";

const labels: Record<string, string> = { CANCELLED: "لغو و بازگردانی موجودی", PROCESSING: "شروع پردازش", SHIPPED: "ثبت ارسال", COMPLETED: "تکمیل سفارش", REFUNDED: "ثبت بازپرداخت و آزادسازی موجودی" };
const input = "h-11 w-full rounded-xl border border-[#cfb45f]/20 bg-[#031a13] px-3 text-sm text-[#f7e7c2] outline-none focus:border-[#dfc36d]/60";
export function AdminOrderWorkflow({ orderId, locale, status, workflowSaved, workflowError, shipmentSaved, shipmentError, latestShipment }: { orderId: string; locale: "fa"|"en"; status: string; workflowSaved: boolean; workflowError?: string; shipmentSaved: boolean; shipmentError?: string; latestShipment?: { carrier?: string; trackingCode?: string; note?: string } }) {
  const transitions = availableAdminTransitions(status);
  return <section className="grid gap-5 xl:grid-cols-2">
    <article className="rounded-[24px] border border-[#d0b359]/15 bg-[#041d15]/82 p-5"><h2 className="flex items-center gap-2 font-semibold text-[#efd782]"><PackageCheck className="size-5"/>گردش‌کار سفارش</h2><p className="mt-2 text-xs leading-6 text-[#91866f]">تغییرها محدود به مسیر امن سفارش هستند و در تاریخچه ثبت می‌شوند.</p>{workflowSaved ? <p className="mt-4 rounded-xl bg-emerald-950/20 p-3 text-sm text-emerald-100">وضعیت ذخیره شد.</p> : null}{workflowError ? <p className="mt-4 rounded-xl bg-red-950/20 p-3 text-sm text-red-100">{workflowError}</p> : null}
      {transitions.length ? <form action={transitionAdminOrderAction.bind(null, orderId, locale)} className="mt-4 space-y-3"><select className={input} name="target" required><option value="">انتخاب وضعیت بعدی</option>{transitions.map(t => <option key={t} value={t}>{labels[t]}</option>)}</select><textarea className={`${input} min-h-24 py-3`} name="note" placeholder="یادداشت مدیر (اختیاری)"/><button className="inline-flex h-11 items-center gap-2 rounded-xl bg-[linear-gradient(135deg,#a98a36,#e4c96f)] px-5 text-sm font-semibold text-[#10251c]"><Save className="size-4"/>ثبت تغییر</button></form> : <p className="mt-4 text-sm text-[#91866f]">برای این وضعیت، تغییر دستی مجاز تعریف نشده است.</p>}
    </article>
    <article className="rounded-[24px] border border-[#d0b359]/15 bg-[#041d15]/82 p-5"><h2 className="flex items-center gap-2 font-semibold text-[#efd782]"><Truck className="size-5"/>اطلاعات ارسال</h2>{shipmentSaved ? <p className="mt-4 rounded-xl bg-emerald-950/20 p-3 text-sm text-emerald-100">اطلاعات ارسال ذخیره شد.</p> : null}{shipmentError ? <p className="mt-4 rounded-xl bg-red-950/20 p-3 text-sm text-red-100">{shipmentError}</p> : null}<form action={saveAdminShipmentAction.bind(null, orderId, locale)} className="mt-4 space-y-3"><input className={input} defaultValue={latestShipment?.carrier ?? ""} name="carrier" placeholder="شرکت یا روش ارسال" required/><input className={input} defaultValue={latestShipment?.trackingCode ?? ""} dir="ltr" name="trackingCode" placeholder="کد رهگیری" required/><textarea className={`${input} min-h-20 py-3`} defaultValue={latestShipment?.note ?? ""} name="note" placeholder="یادداشت ارسال"/><button className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#d2b65e]/20 bg-[#d0b258]/8 px-5 text-sm text-[#e0c875]"><Truck className="size-4"/>ذخیره ارسال</button></form></article>
  </section>;
}
