import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ArticleMarkdown } from "../src/components/article-markdown";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { normalizePersianArticle, normalizePersianSeo, factualImageAlt, safeArticleHref, plainSeoText } from "../src/lib/seo-content-tools";
const require = createRequire(import.meta.url);
async function main() {
  Object.assign(process.env,{NODE_ENV:"test",DATABASE_URL:"postgresql://test:test@127.0.0.1:5432/test"});
  const { inspectSeoHtml } = await import("../src/lib/seo-page-scan");
  const rendered = renderToStaticMarkup(createElement(ArticleMarkdown, { value: "## Test\n\n[Product](/fa/products/test) **Bold**\n\n![Ring](/images/ring.webp)" }));
  assert.ok(rendered.includes('href="/fa/products/test"'));
  assert.ok(rendered.includes('<strong>Bold</strong>'));
  assert.ok(rendered.includes('alt="Ring"'));
  const unsafe = renderToStaticMarkup(createElement(ArticleMarkdown, {value:"[x](javascript:alert)"}));
  assert.equal(unsafe.includes('href="javascript'),false);
  assert.equal(normalizePersianSeo("كالا ي ، تست"), "کالا ی، تست");
  assert.equal(normalizePersianArticle("مي شود [لينك](https://example.com/ي) `ي`"), "می‌شود [لینک](https://example.com/ي) `ي`");
  assert.equal(factualImageAlt("انگشتر", "fa"), "انگشتر");
  for (const value of ["javascript:alert(1)","//evil.test","/\\evil.test","data:text/html,x"]) assert.equal(safeArticleHref(value),null);
  assert.equal(safeArticleHref("/fa/products/test"),"/fa/products/test");
  assert.equal(plainSeoText("**Text** [name](/fa)"),"Text name");
  const audit = inspectSeoHtml('<title>Test</title><h1>A</h1><img src="a"><script type="application/ld+json">bad</script>',"https://example.com/fa");
  assert.equal(audit.missingAlt,1);assert.ok(audit.findings.some(f=>f.includes("JSON-LD")));
  Object.assign(process.env,{NODE_ENV:"test",DATABASE_URL:"postgresql://test:test@127.0.0.1:5432/test"});
  require("next/cache").revalidatePath = () => {};
  const { prisma } = await import("../src/lib/prisma");
  const { repairSeoBatch } = await import("../src/lib/seo-autopilot");
  const article = {id:"a",slug:"test",titleFa:"عنوان",titleEn:"Title",excerptFa:"توضیح واقعی",excerptEn:"Real description",contentFa:"مي شود",contentEn:"body",seoTitleFa:null,seoTitleEn:null,seoDescriptionFa:null,seoDescriptionEn:null,coverImageUrl:null,sourceProduct:{images:[{imageUrl:"/images/test.webp"}]},auditEvents:[],updatedAt:new Date()};
  const image = {id:"i",productId:"p",altFa:null,altEn:null,updatedAt:new Date(),product:{nameFa:"نام واقعی",nameEn:"Real name",slug:"test",timelineEvents:[]}};
  const events: unknown[]=[];let conflict=false;
  prisma.contentArticle.findMany=(async()=>[article]) as unknown as typeof prisma.contentArticle.findMany;
  prisma.productImage.findMany=(async()=>[image]) as unknown as typeof prisma.productImage.findMany;
  const update = (record:object) => async({data}:{data:object})=>{if(conflict)return {count:0};Object.assign(record,data);return {count:1};};
  const tx={contentArticle:{updateMany:update(article)},productImage:{updateMany:update(image)},contentArticleAuditEvent:{create:async(v:unknown)=>events.push(v)},productTimelineEvent:{create:async(v:unknown)=>events.push(v)}};
  prisma.$transaction=(async(fn:(t:typeof tx)=>Promise<unknown>)=>fn(tx)) as unknown as typeof prisma.$transaction;
  assert.equal((await repairSeoBatch()).changed,2);assert.equal(events.length,2);
  assert.equal(article.contentFa,"می‌شود");assert.equal(article.coverImageUrl,"/images/test.webp");
  assert.equal((await repairSeoBatch()).changed,0,"Second run must not rewrite unchanged records");
  image.altFa=null;conflict=true;assert.equal((await repairSeoBatch()).changed,0);assert.equal(events.length,2,"No audit event for rejected concurrent update");
  conflict=false;image.product.timelineEvents.push({} as never);assert.equal((await repairSeoBatch()).changed,0,"Restored products must stay opted out");
  process.env.ELORIA_SEO_AUTOPILOT_ENABLED="false";assert.equal((await repairSeoBatch()).disabled,true);
  await prisma.$disconnect();console.log("PASS: text preservation, safe links, HTML checks, repair idempotence, concurrent edit protection and restore opt-out (mock persistence)");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
