import type { Metadata } from "next";
import type { ReactNode } from "react";

import "../globals.css";

import { hasLocale, NextIntlClientProvider } from "next-intl";

import {
  getTranslations,
  setRequestLocale,
  getMessages,
} from "next-intl/server";

import { notFound } from "next/navigation";
import { connection } from "next/server";

import { PageBackgroundProvider } from "@/components/page-background-provider";
import { DeferredSiteTools } from "@/components/deferred-site-tools";
import { SiteMeasurementTracker } from "@/components/site-measurement-tracker";
import { SiteStructuredData } from "@/components/site-structured-data";
import { PwaRegistration } from "@/components/pwa-registration";
import { MarketingAttributionTracker } from "@/components/marketing-attribution-tracker";
import { NavigationAccelerator } from "@/components/navigation-accelerator";

import { routing } from "@/i18n/routing";
import { siteBaseUrl } from "@/lib/site-url";
import { isSiteMeasurementEnabled } from "@/lib/site-measurement";

type LocaleParams = Promise<{
  locale: string;
}>;

type LocaleLayoutProps = Readonly<{
  children: ReactNode;
  params: LocaleParams;
}>;

export function generateStaticParams() {
  return routing.locales.map((locale) => ({
    locale,
  }));
}

export async function generateMetadata({
  params,
}: {
  params: LocaleParams;
}): Promise<Metadata> {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    return {};
  }

  const t = await getTranslations({
    locale,
    namespace: "Metadata",
  });

  const baseUrl = siteBaseUrl();

  const defaultTitle = t("title");
  // eNamad requires this value only during its title-verification step. Keep
  // the switch server-side so it cannot be toggled by a visitor.
  const title =
    process.env.ELORIA_ENAMAD_TITLE_VERIFICATION === "true"
      ? `${defaultTitle} | 26263305`
      : defaultTitle;
  const description = t("description");

  return {
    metadataBase: baseUrl,
    title,
    description,
    // Renders exactly: <meta name="enamad" content="26263305" />
    other: {
      enamad: "26263305",
    },

    alternates: {
      canonical: `/${locale}`,
      languages: {
        fa: "/fa",
        en: "/en",
        "x-default": "/fa",
      },
    },

    openGraph: {
      type: "website",
      siteName: "ELORIA",
      locale: locale === "fa" ? "fa_IR" : "en_US",
      alternateLocale: locale === "fa" ? ["en_US"] : ["fa_IR"],
      title,
      description,
      url: `/${locale}`,
      images: [
        {
          url: "/images/hero/eloria-hero.jpeg",
          width: 1600,
          height: 900,
          alt: title,
        },
      ],
    },

    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["/images/hero/eloria-hero.jpeg"],
    },
  };
}

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  // The nonce generated by src/proxy.ts is request-specific. Waiting for the
  // connection makes every localized document render with the matching nonce
  // instead of serving a static document that could not safely use it.
  await connection();
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html
      data-scroll-behavior="smooth"
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className="min-h-screen">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <PageBackgroundProvider>
            <SiteStructuredData />
            <PwaRegistration />
            <MarketingAttributionTracker />
            <NavigationAccelerator />
            <SiteMeasurementTracker
              locale={locale}
              enabled={isSiteMeasurementEnabled()}
            />
            {children}
            <DeferredSiteTools locale={locale} />
          </PageBackgroundProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
